### ISSUE TITLE
Poll command is okay with no options and has improper empty title formatting

### ISSUE THREAD

**Issue by camd67** [camd67/moebot#10]
1. When a user provides no options for a poll, it still goes through but gives no options for users to vote on. The command should return an error when `options count <= 1` (since 1 option also seems like a pointless poll)
2. Creating a poll with no title creates the following text: `@User created the poll **!` The stars are a bug, and it should probably just go with `@User created a poll!` when title is missing.

**Comment by Shadran** [comment]
Fixed with https://github.com/camd67/moebot/pull/12
