### ISSUE TITLE
Spoiler text gets cut off on certain strings

### ISSUE THREAD

**Issue by camd67** [camd67/moebot#11]
![image](https://user-images.githubusercontent.com/7773345/34707565-15f9a856-f4c3-11e7-87ef-478de05a4fc4.png) (should be `kowz needs to get a sleep schedule`)
Spoiler text seems to be cut off for certain strings. Needs further testing to see if this is just long strings or specific lengths

**Comment by Shadran** [comment]
Fixed with https://github.com/camd67/moebot/pull/12
