### ISSUE TITLE
Moon Whistle

### ISSUE THREAD

**Issue by camd67** [camd67/moebot#17]
* 10,000 points for role request
* 50 points for first post of the day
* 5 points per post after that
* 2 points per react

After getting 10,000 points ask the user if they want the role in #bot-stuff.

**Comment by Shadran** [comment]
Might also want to add a "cooldown" to points gained through reactions, to avoid reaction spamming

**Comment by camd67** [comment]
True. We had discussed that for messages but not for reactions. I'll bring that up with the other mods.
I wanted reactions to count since (being biased here) lurkers may want moon whistle too and may not like talking a lot but still try to participate in other ways. I'll see if lowering the react points to 1 or adding a cooldown would work.
