### ISSUE TITLE
Spoilers with large amounts of text become unreadable unless zoomed in on large screens

### ISSUE THREAD

**Issue by camd67** [camd67/moebot#21]
![image](https://user-images.githubusercontent.com/7773345/35083199-d23e8872-fbd2-11e7-99ae-3d0cddee716a.png)

**Comment by Shadran** [comment]
This is a problem on how discord resizes images to fit its window. I could try to play with maximum width, font size and other settings to see if it reduces the problem. What was the screen resolution?

**Comment by camd67** [comment]
this is on a 1920x1080 monitor (you should know the actual text) not zoomed in. Zoomed in it looks fine.
Maybe we could increase the font weight + size?

Note this is _only_ for long strings
