### ISSUE TITLE
Help command displays commands with multiple aliases once for each alias

### ISSUE THREAD

**Issue by efevans** [camd67/moebot#45]
If a command specifies multiple keys in the` GetCommandKeys()` method, each key is stored in the commands map. The `help` command iterates through the map, so it will call a the command's `GetCommandHelp()` for each alias.

**Comment by camd67** [comment]
Good catch, this was overlooked during the initial help implementation probably because we didn't use aliases.

My stance on this would be to take in the commands slice instead of the commands map and pull out the command keys from that instead.
